language: dart

dart:
  - dev
  - stable

dart_task:
  - test: --platform vm
  - test: --platform firefox
  - test: --platform chrome
  - dartanalyzer

matrix:
  include:
    - dart: dev
      dart_task: dartfmt
  # TODO(travis-ci/travis-ci#8836): Remove once the travis issue is resolved.
  allow_failures:
    - dart_task:
        test: --platform chrome

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
