language: dart

dart:
  - dev
  - 2.0.0

dart_task:
  - test: --platform vm
  - test: --platform chrome
  - dartanalyzer: --fatal-infos --fatal-warnings .

matrix:
  include:
    - dart: dev
      dart_task: dartfmt

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
